export interface Set {
  id?: number; // Optional because it will be generated by the database
  reps: number;
  weight: number;
  rest: number | null;
}

export interface Exercise {
  id?: number;
  name: string;
  description: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ExerciseInstance {
  id?: number;
  sets: Set[];
  exercise: {
    data: Exercise;
  };
  createdAt: Date;
  updatedAt: Date;
}

export interface Session {
  id?: number;
  name: string;
  description: string;
  date: Date;
  isPreset: boolean;
  exercise_instances: {
    data: ExerciseInstance[];
  };
  createdAt: Date;
  updatedAt: Date;
}
